// src/lib/pdf.ts
export async function generateReviewPackPDF(
  walletAddress: string,
  chain: string,
  transfers: any[],
  stablecoinSummary: { received: number; sent: number; netFlow: number; breakdown: Record<string, any> },
  brief: string,
  labels: Record<string, string>
) {
  const reportHTML = buildReportHTML(walletAddress, chain, transfers, stablecoinSummary, brief, labels);

  // Open a new window and write the report directly to it
  const win = window.open("", "_blank", "width=800,height=600");
  if (!win) {
    alert("Please allow pop‑ups to generate the review pack.");
    return;
  }
  win.document.write(`
    <html>
      <head>
        <title>TxDocket Review Pack</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            color: #000;
            background: #fff;
            padding: 20px;
          }
          @media print {
            @page { margin: 10mm; size: A4; }
          }
        </style>
      </head>
      <body>
        ${reportHTML}
      </body>
    </html>
  `);
  win.document.close();

  // Wait for the document to fully load, then trigger print
  await new Promise(resolve => setTimeout(resolve, 800));
  win.print();
}

// buildReportHTML remains exactly the same as before
function buildReportHTML(
  walletAddress: string,
  chain: string,
  transfers: any[],
  stablecoinSummary: any,
  brief: string,
  labels: Record<string, string>
): string {
  const rowsHTML = transfers.map((tx, idx) => {
    const isIncoming = tx.to.toLowerCase() === walletAddress.toLowerCase();
    const isOutgoing = tx.from.toLowerCase() === walletAddress.toLowerCase();
    let direction = "";
    if (isIncoming && !isOutgoing) direction = "In";
    else if (isOutgoing && !isIncoming) direction = "Out";
    else if (isIncoming && isOutgoing) direction = "Self";
    else direction = "?";

    const fromLabel = labels[tx.from.toLowerCase()] || `${tx.from.slice(0,6)}...${tx.from.slice(-4)}`;
    const toLabel = labels[tx.to.toLowerCase()] || `${tx.to.slice(0,6)}...${tx.to.slice(-4)}`;

    return `
      <tr>
        <td>${tx.date}</td>
        <td>${tx.token}</td>
        <td style="text-align:right">${tx.amount}</td>
        <td style="color:${direction==="In"?"green":direction==="Out"?"red":"gray"}">${direction}</td>
        <td>${fromLabel}</td>
        <td>${toLabel}</td>
        <td style="font-size:10px">${tx.txHash?.slice(0,10)}…</td>
      </tr>
    `;
  }).join("");

  return `
    <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px;">
      <h1 style="font-size: 24px; margin-bottom: 4px;">TxDocket Review Pack</h1>
      <p style="margin-top:0; color: #555;">Wallet: ${walletAddress} &nbsp;|&nbsp; Chain: ${chain} &nbsp;|&nbsp; Date: ${new Date().toISOString().split("T")[0]}</p>

      <div style="margin: 20px 0; padding: 15px; background: #f5f5f5; border-radius: 8px;">
        <h2 style="font-size: 18px; margin-bottom: 12px;">💵 Stablecoin Flow Summary</h2>
        <div style="display: flex; gap: 30px; margin-bottom: 12px;">
          <div><strong>Total Received:</strong> $${stablecoinSummary.received.toFixed(2)}</div>
          <div><strong>Total Sent:</strong> $${stablecoinSummary.sent.toFixed(2)}</div>
          <div><strong>Net Flow:</strong> $${stablecoinSummary.netFlow.toFixed(2)}</div>
        </div>
        ${Object.entries(stablecoinSummary.breakdown).map(([sym, data]: any) => `
          <div style="font-size: 14px; margin: 4px 0;">
            <strong>${sym}:</strong> +$${data.received.toFixed(2)} / -$${data.sent.toFixed(2)}
          </div>
        `).join("")}
      </div>

      <div style="margin: 20px 0; padding: 15px; background: #f9f9ff; border-radius: 8px;">
        <h2 style="font-size: 18px; margin-bottom: 12px;">📋 TxDocket Brief</h2>
        <div style="white-space: pre-line; font-size: 14px; line-height: 1.5;">${brief ? brief.replace(/\n/g, "<br>") : "<p>No brief generated.</p>"}</div>
      </div>

      <h2 style="font-size: 18px; margin-top: 24px;">Transaction Schedule</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 8px;">
        <thead>
          <tr style="background: #eee;">
            <th>Date</th><th>Token</th><th>Amount</th><th>Dir</th><th>From</th><th>To</th><th>Tx Hash</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHTML}
        </tbody>
      </table>

      <p style="font-size: 10px; color: #888; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 12px;">
        This report was generated by TxDocket (https://txdocket.vercel.app). It is AI-assisted and does not constitute financial, tax, or legal advice.
      </p>
    </div>
  `;
}